config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout', :sign_up => 'register'},
     :controllers => {:sessions => 'sessions', :registrations => 'registrations', :passwords => 'passwords'}
   devise_scope :user do
     get "/users/sign_in", :to => "sessions#new"
   end

   authenticated :user do
     devise_scope :user do
       root to: "users#index", as: "auth_root"
     end
   end
   unauthenticated do
     devise_scope :user do
       root to: "sessions#new", as: "unauth_root"
     end
   end
   root to: "pages#index"
   
   
  resources :goods

  resources :relief_centres

  resources :users

end

app/models/relief_centre.rb
class ReliefCentre < ActiveRecord::Base
  
  has_and_belongs_to_many :users
  has_many :goods
end

app/controllers/relief_centres_controller.rb
class ReliefCentresController < ApplicationController
  before_action :set_relief_centre, only: [:show, :edit, :update, :destroy]

  # GET /relief_centres
  # GET /relief_centres.json
  def index
    @relief_centres = ReliefCentre.all
  end

  # GET /relief_centres/1
  # GET /relief_centres/1.json
  def show
  end

  # GET /relief_centres/new
  def new
    @relief_centre = ReliefCentre.new
    @users = User.all
  end

  # GET /relief_centres/1/edit
  def edit
  end

  # POST /relief_centres
  # POST /relief_centres.json
  def create
    @relief_centre = ReliefCentre.new(relief_centre_params)


    respond_to do |format|
      if @relief_centre.save
        format.html { redirect_to relief_centres_path, notice: 'Relief centre was successfully created.' }
        format.json { render :show, status: :created, location: @relief_centre }
      else
        format.html { render :new }
        format.json { render json: @relief_centre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /relief_centres/1
  # PATCH/PUT /relief_centres/1.json
  def update
    respond_to do |format|
      if @relief_centre.update(relief_centre_params)
        format.html { redirect_to relief_centres_path, notice: 'Relief centre was successfully updated.' }
        format.json { render :show, status: :ok, location: @relief_centre }
      else
        format.html { render :edit }
        format.json { render json: @relief_centre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /relief_centres/1
  # DELETE /relief_centres/1.json
  def destroy
    @relief_centre.destroy
    respond_to do |format|
      format.html { redirect_to relief_centres_url, notice: 'Relief centre was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_relief_centre
      @relief_centre = ReliefCentre.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def relief_centre_params
      params.require(:relief_centre).permit(:name, :address, :gps_coordinate, :mukim, :district, :user_ids => [])
    end
end

app/helpers/relief_centres_helper.rb
module ReliefCentresHelper
end

app/views/relief_centres/_form.html.erb
<%= form_for(@relief_centre) do |f| %>
  <% if @relief_centre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@relief_centre.errors.count, "error") %> prohibited this relief_centre from being saved:</h2>

      <ul>
      <% @relief_centre.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "Nama Pusat Pemindahan" %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address, "Alamat" %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :gps_coordinate, "Koordinat GPS" %><br>
    <%= f.text_field :gps_coordinate %>
  </div>
  <div class="field">
    <%= f.label :district %><br>
    <%= f.text_field :district %>
  </div>
  <div class="field">
    <%= f.label :mukim %><br>
    <%= f.text_field :mukim %>
  </div>
  <div class="field">
    <%= f.label "Pegawai Dihubungi" %><br>
  </div>

  <div class="field">
    <% for user in User.all %>
       <tr>
         <td><%= check_box_tag "relief_centre[user_ids][]", user.id, @relief_centre.users.include?(user) %></td>
         <td><%= user.name %></td>
       </tr>
     <% end %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/relief_centres/edit.html.erb
<h1>Editing relief_centre</h1>

<%= render 'form' %>

<%= link_to 'Show', @relief_centre %> |
<%= link_to 'Back', relief_centres_path %>

app/views/relief_centres/index.html.erb
<h1>Listing relief_centres</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Gps coordinate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @relief_centres.each do |relief_centre| %>
      <tr>
        <td><%= relief_centre.name %></td>
        <td><%= relief_centre.address %></td>
        <td><%= relief_centre.gps_coordinate %></td>
        <td><%= link_to 'Show', relief_centre %></td>
        <td><%= link_to 'Edit', edit_relief_centre_path(relief_centre) %></td>
        <td><%= link_to 'Destroy', relief_centre, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Relief centre', new_relief_centre_path %>

app/views/relief_centres/new.html.erb
<h1>New relief_centre</h1>

<%= render 'form' %>

<%= link_to 'Back', relief_centres_path %>

app/views/relief_centres/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @relief_centre.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @relief_centre.address %>
</p>

<p>
  <strong>Gps coordinate:</strong>
  <%= @relief_centre.gps_coordinate %>
</p>

<%= link_to 'Edit', edit_relief_centre_path(@relief_centre) %> |
<%= link_to 'Back', relief_centres_path %>