config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout', :sign_up => 'register'},
     :controllers => {:sessions => 'sessions', :registrations => 'registrations', :passwords => 'passwords'}
   devise_scope :user do
     get "/users/sign_in", :to => "sessions#new"
   end

   authenticated :user do
     devise_scope :user do
       root to: "users#index", as: "auth_root"
     end
   end
   unauthenticated do
     devise_scope :user do
       root to: "sessions#new", as: "unauth_root"
     end
   end
   root to: "pages#index"
   
   
  resources :goods

  resources :relief_centres

  resources :users

end

app/models/good.rb
class Good < ActiveRecord::Base
  
  belongs_to :user, :class_name => "User", :foreign_key => "contact_person_id"
  belongs_to :relief_centre, :class_name => "ReliefCentre", :foreign_key => "relief_centre_id"
end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController
  before_action :set_good, only: [:show, :edit, :update, :destroy]

  # GET /goods
  # GET /goods.json
  def index
    @goods = Good.all
  end

  # GET /goods/1
  # GET /goods/1.json
  def show
  end

  # GET /goods/new
  def new
    @good = Good.new
  end

  # GET /goods/1/edit
  def edit
  end

  # POST /goods
  # POST /goods.json
  def create
    @good = Good.new(good_params)

    respond_to do |format|
      if @good.save
        format.html { redirect_to goods_path, notice: 'Good was successfully created.' }
        format.json { render :show, status: :created, location: @good }
      else
        format.html { render :new }
        format.json { render json: @good.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /goods/1
  # PATCH/PUT /goods/1.json
  def update
    respond_to do |format|
      if @good.update(good_params)
        format.html { redirect_to goods_path, notice: 'Good was successfully updated.' }
        format.json { render :show, status: :ok, location: @good }
      else
        format.html { render :edit }
        format.json { render json: @good.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goods/1
  # DELETE /goods/1.json
  def destroy
    @good.destroy
    respond_to do |format|
      format.html { redirect_to goods_url, notice: 'Good was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_good
      @good = Good.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def good_params
      params.require(:good).permit(:item, :quantity, :received_date, :received_from, :relief_centre_id)
    end
end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/views/goods/_form.html.erb
<%= form_for(@good) do |f| %>
  <% if @good.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@good.errors.count, "error") %> prohibited this good from being saved:</h2>

      <ul>
      <% @good.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :item %><br>
    <%= f.text_field :item %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.text_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :received_date %><br>
    <%= f.date_select :received_date %>
  </div>
  <div class="field">
    <%= f.label :relief_centre_id %><br>
    <%= f.select(:relief_centre_id, ReliefCentre.all.collect {|p| [ p.name, p.id ] }, {prompt: 'Pilih Pusat Pemindahan'}) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/goods/edit.html.erb
<h1>Editing good</h1>

<%= render 'form' %>

<%= link_to 'Show', @good %> |
<%= link_to 'Back', goods_path %>

app/views/goods/index.html.erb
<h1>Listing goods</h1>

<table>
  <thead>
    <tr>
      <th>Item</th>
      <th>Quantity</th>
      <th>Received date</th>
      <th>Received from</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @goods.each do |good| %>
      <tr>
        <td><%= good.item %></td>
        <td><%= good.quantity %></td>
        <td><%= good.received_date %></td>
        <td><%= good.received_from %></td>
        <td><%= link_to 'Show', good %></td>
        <td><%= link_to 'Edit', edit_good_path(good) %></td>
        <td><%= link_to 'Destroy', good, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Good', new_good_path %>

app/views/goods/new.html.erb
<h1>New good</h1>

<%= render 'form' %>

<%= link_to 'Back', goods_path %>

app/views/goods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Item:</strong>
  <%= @good.item %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @good.quantity %>
</p>

<p>
  <strong>Received date:</strong>
  <%= @good.received_date %>
</p>

<p>
  <strong>Received from:</strong>
  <%= @good.received_from %>
</p>

<%= link_to 'Edit', edit_good_path(@good) %> |
<%= link_to 'Back', goods_path %>